apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache 
  ports:
    - protocol: TCP
      port: 8081 
      targetPort: 80 
      nodePort: 30081 
  type: NodePort 